repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: elastic
  url: https://helm.elastic.co
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: eks
  url: https://aws.github.io/eks-charts
- name: falcosecurity
  url: https://falcosecurity.github.io/charts

releases:
  - name: alb-ingress-controller
    namespace: kube-system
    labels:
      namespace: kube-system
    chart: eks/aws-load-balancer-controller
    set:
    - name: serviceAccount.create
      value: true
    - name: serviceAccount.name
      value: aws-load-balancer-controller
    - name: 'serviceAccount.annotations.eks\.amazonaws\.com/role-arn'
      value: ref+awsssm://blackbelt/blackbelt-eks_utils/alb_controller_role_arn
    - name: clusterName
      value: blackbelt-eks

  - name: logstash
    namespace: logging
    labels:
      namespace: logging
    chart: elastic/logstash
    values:
      - "values/logstash.yaml"
    set:
    - name: extraEnvs[0].name
      value: "ELASTICSEARCH_HOST"
    - name: extraEnvs[0].value
      value: ref+awsssm://blackbelt/eks-logging-elasticsearch/endpoint
    - name: extraEnvs[1].name
      value: "ELASTICSEARCH_USER"
    - name: extraEnvs[1].value
      value: ref+awsssm://blackbelt/eks-logging-elasticsearch/admin_username
    - name: extraEnvs[2].name
      value: "ELASTICSEARCH_PASSWORD"
    - name: extraEnvs[2].value
      value: ref+awsssm://blackbelt/eks-logging-elasticsearch/admin_password

  - name: filebeat
    namespace: logging
    labels:
      namespace: logging
    chart: elastic/filebeat
    values:
      - "values/filebeat.yaml"

  - name: prometheus
    namespace: monitoring
    labels:
      namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - "values/prometheus.yaml"
    set:
    - name: server.remoteWrite[0].url
      value: ref+awsssm://blackbelt/eks-monitoring/endpoint
    - name: server.remoteWrite[0].sigv4.region
      value: eu-central-1
    - name: 'serviceAccounts.server.annotations.eks\.amazonaws\.com/role-arn'
      value: ref+awsssm://blackbelt/eks-monitoring/role_arn

  - name: grafana
    namespace: monitoring
    chart:  grafana/grafana
    labels:
      role: display
      namespace: monitoring
    values:
      - "values/grafana.yaml"
    set:
      - name: adminPassword
        value: ref+awsssm://blackbelt/eks-monitoring/grafana_password
      - name: 'grafana\.ini.database.type'
        value: mysql
      - name: 'grafana\.ini.database.url'
        value: mysql://root:ref+awsssm://blackbelt/eks-monitoring/grafana_db_password+@mariadb:3306/grafana

  - name: mariadb
    namespace: monitoring
    chart:  bitnami/mariadb
    labels:
      role: persistence
      namespace: monitoring
    values:
      - "values/mariadb.yaml"
    set:
      - name: auth.rootPassword
        value: ref+awsssm://blackbelt/eks-monitoring/grafana_db_password

  - name: falco
    namespace: security
    labels:
      namespace: security
    chart: falcosecurity/falco
    values:
      - "values/falco.yaml"
    set:
      - name: falcosidekick.config.elasticsearch.hostport
        value: https://ref+awsssm://blackbelt/eks-logging-elasticsearch/endpoint+:443
      - name: falcosidekick.config.elasticsearch.username
        value: ref+awsssm://blackbelt/eks-logging-elasticsearch/admin_username
      - name: falcosidekick.config.elasticsearch.password
        value: ref+awsssm://blackbelt/eks-logging-elasticsearch/admin_password

  - name: falco-exporter
    namespace: security
    labels:
      namespace: security
    chart: falcosecurity/falco-exporter
    values:
      - "values/falco-exporter.yaml"