repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: elastic
  url: https://helm.elastic.co

releases:
  - name: node-exporter
    namespace: monitoring
    labels:
      namespace: monitoring
    chart: prometheus-community/prometheus-node-exporter
  - name: logstash
    namespace: logging
    labels:
      namespace: logging
    chart: elastic/logstash
    values:
      - "values/logstash.yaml"
    set:
    - name: extraEnvs[0].name
      value: "ELASTICSEARCH_HOST"
    - name: extraEnvs[0].value
      value: ref+awsssm://blackbelt/eks_logging/endpoint
    - name: extraEnvs[1].name
      value: "ELASTICSEARCH_USER"
    - name: extraEnvs[1].value
      value: ref+awsssm://blackbelt/eks_logging/admin_username
    - name: extraEnvs[2].name
      value: "ELASTICSEARCH_PASSWORD"
    - name: extraEnvs[2].value
      value: ref+awsssm://blackbelt/eks_logging/admin_password
  - name: filebeat
    namespace: logging
    labels:
      namespace: logging
    chart: elastic/filebeat
    values:
      - "values/filebeat.yaml"
  - name: prometheus
    namespace: monitoring
    labels:
      namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - "values/prometheus.yaml"
    set:
    - name: server.remoteWrite[0].url
      value: ref+awsssm://blackbelt/eks_monitoring/endpoint
    - name: server.remoteWrite[0].sigv4.region
      value: eu-central-1