repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: elastic
  url: https://helm.elastic.co
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: incubator
  url: http://storage.googleapis.com/kubernetes-charts-incubator

releases:
  - name: alb-ingress-controller
    namespace: kube-system
    labels:
      namespace: kube-system
    chart: incubator/aws-alb-ingress-controller
    set:
    - name: autoDiscoverAwsRegion
      value: true
    - name: autoDiscoverAwsVpcID
      value: true
    - name: clusterName
      value: blackbelt-eks

  - name: logstash
    namespace: logging
    labels:
      namespace: logging
    chart: elastic/logstash
    values:
      - "values/logstash.yaml"
    set:
    - name: extraEnvs[0].name
      value: "ELASTICSEARCH_HOST"
    - name: extraEnvs[0].value
      value: ref+awsssm://blackbelt/eks_logging/endpoint
    - name: extraEnvs[1].name
      value: "ELASTICSEARCH_USER"
    - name: extraEnvs[1].value
      value: ref+awsssm://blackbelt/eks_logging/admin_username
    - name: extraEnvs[2].name
      value: "ELASTICSEARCH_PASSWORD"
    - name: extraEnvs[2].value
      value: ref+awsssm://blackbelt/eks_logging/admin_password

  - name: filebeat
    namespace: logging
    labels:
      namespace: logging
    chart: elastic/filebeat
    values:
      - "values/filebeat.yaml"

  - name: prometheus
    namespace: monitoring
    labels:
      namespace: monitoring
    chart: prometheus-community/prometheus
    values:
      - "values/prometheus.yaml"
    set:
    - name: server.remoteWrite[0].url
      value: ref+awsssm://blackbelt/eks_monitoring/endpoint
    - name: server.remoteWrite[0].sigv4.region
      value: eu-central-1
    - name: 'serviceAccounts.server.annotations.eks\.amazonaws\.com/role-arn'
      value: ref+awsssm://blackbelt/eks_monitoring/role_arn

  - name: grafana
    namespace: monitoring
    chart:  grafana/grafana
    labels:
      role: display
      namespace: monitoring
    values:
      - "values/grafana.yaml"
    set:
      - name: adminPassword
        value: ref+awsssm://blackbelt/eks_monitoring/grafana_password
      - name: 'grafana\.ini.database.type'
        value: mysql
      - name: 'grafana\.ini.database.url'
        value: mysql://root:ref+awsssm://blackbelt/eks_monitoring/grafana_db_password+@mariadb:3306/grafana

  - name: mariadb
    namespace: monitoring
    chart:  bitnami/mariadb
    labels:
      role: persistence
      namespace: monitoring
    values:
      - "values/mariadb.yaml"
    set:
      - name: auth.rootPassword
        value: ref+awsssm://blackbelt/eks_monitoring/grafana_db_password